config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
  end
  root to: 'homes#top'
  #get 'books' => 'books#index'
  get 'home/about' => 'homes#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource) 
    user_path(current_user.id)
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id), notice: 'You have created book successfully..'
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully'
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to book_path(book)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end  
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render 'edit'
    end  
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div id="error_explanation">
          <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model:@book, url: book_path(params[:id]), local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: 'form-control' %>
        </div>
        <div class="form-group">
          <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
        </div>
      <% end %>
      <%= link_to "Show", book_path %>|
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<br>


<div class="container px-5 px-sm-0">

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="row">

    <%= render 'users/profile', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%=  notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

<br>

      <div class="row">
        <%= link_to "", edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model:@new_book, url:'/books', local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <input class="form-control book_title" type="text" name="book[title]" id="book_title">
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
        </div>
        <div class="form-group">
          <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg" %><br>
              <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to "Destroy", "/books/#{@book.id}", class: 'btn btn-sm btn-danger', method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            <% end %>
            <% if @book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  ★<%= @book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  ☆<%= @book.favorites.count %>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<br>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="logout-message">
<% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>
  <% end %>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block md-3 sign_in' %>
          
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/f2c44be854.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Bookers2</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %></li>
                <li><%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %></li>
                <li><%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %></li>
                <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %></li>
              <% else %>
                <li><%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %></li>
                <li><%= link_to " About", home_about_path, class: 'fas fa-link nav-link text-light' %></li>
                <li><%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %></li>
                <li><%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_profile.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
  <br>

  <div class="row">
  <%= link_to  "", edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model:@book, url:'/books', local:true do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <input class="form-control book_title" type="text" name="book[title]" id="book_title">
    </div>
    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
    </div>
    <div class="form-group">
      <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
        </div>
        <%= f.text_field :name %>
        <div class="form-group">
          <label for="user_image">Image</label>
        </div>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
        </div>
        <%= f.text_area :introduction %>
        <div class="form-group">
          <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<br>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/profile', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%=  notice %></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/profile', user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tbody>
            <tr>
              <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>